/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Itinerarios;

import Dao.Class.Funcionario;
import Dao.Class.Linha;
import Dao.Controller.FuncionarioControlador;
import Dao.Controller.LinhaControlador;
import View.MenuPrincipal;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Baroni
 */
public class GerenciarLinhas extends javax.swing.JDialog {
    Funcionario F = new Funcionario();
    FuncionarioControlador FC = new FuncionarioControlador();
    Linha L = new Linha();
    LinhaControlador LC = new LinhaControlador();
    public String usuario;
    /**
     * Creates new form GerenciarLinhas
     */
    public GerenciarLinhas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setValores(){
        setUsuario();
        refresh();
        setPref();
    }
    public void setPref(){
        for (Linha c: LC.buscarPrefx()){
            cbPrefixo.addItem(Integer.toString(c.getPrefixo()));
        }        
    }
    public void setUsuario(){
        F = FC.buscar(usuario);
        String tipo = F.getTipo();
    }
    public void refresh(){
        List<Linha> li = LC.buscarPrefx();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSair = new javax.swing.JButton();
        btInserirPrefixo = new javax.swing.JButton();
        cbPrefixo = new javax.swing.JComboBox<>();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btSair.setText("Fechar");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btInserirPrefixo.setText("Criar Prefixo");
        btInserirPrefixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirPrefixoActionPerformed(evt);
            }
        });

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Prefixo", "Origem", "Destino", "Vl. Tarifa", "Preço"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setMaxWidth(85);
            jTable.getColumnModel().getColumn(3).setMaxWidth(130);
            jTable.getColumnModel().getColumn(4).setMaxWidth(130);
        }

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir Prefixo");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btInserirPrefixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btSair))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar)
                    .addComponent(btInserirPrefixo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        MenuPrincipal form = new MenuPrincipal(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void btInserirPrefixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirPrefixoActionPerformed
        CriarPrefixo form = new CriarPrefixo(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_btInserirPrefixoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        DecimalFormat df = new DecimalFormat("#,###.00");
        int prefixo = Integer.parseInt(cbPrefixo.getSelectedItem().toString());
        List<Linha> li = LC.buscaPrefixo(prefixo);
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        Object rowData[] = new Object[5];
        model.setRowCount(0);
        for(int i =0; i< li.size(); i++){
            rowData[0] = li.get(i).getPrefixo();
            rowData[1] = li.get(i).getCidadeInicial();
            rowData[2] = li.get(i).getCidadeFinal();
            rowData[3] = df.format(li.get(i).getTarifa());
            rowData[4] = df.format(li.get(i).getPrecoTotal());
            model.addRow(rowData);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int linhaSelec = jTable.getSelectedRow();
        if(jTable.getSelectedRow() == -1){
            if(jTable.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Tabela está vazia", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um Perfil !!!", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UpdLinhas form = new UpdLinhas(null, true);
            String idEsc = model.getValueAt(linhaSelec, 0).toString();
            String cid1 = model.getValueAt(linhaSelec, 1).toString();
            String cid2 = model.getValueAt(linhaSelec, 2).toString();
            form.valorId = Integer.parseInt(idEsc);
            form.cidId1 = cid1;
            form.cidId2 = cid2;
            form.usuario = F.getLogin();
            form.setValores();
            this.dispose();
            form.setLocationRelativeTo(null);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void jTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMousePressed
        jTable.editingCanceled(null);
    }//GEN-LAST:event_jTableMousePressed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int linhaSelec = jTable.getSelectedRow();
        if(jTable.getSelectedRow() == -1){
            if(jTable.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Tabela está vazia", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um Perfil !!!", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            String idExc = model.getValueAt(linhaSelec, 0).toString();
            String cid1 = model.getValueAt(linhaSelec, 1).toString();
            String cid2 = model.getValueAt(linhaSelec, 2).toString();
            if (LC.excluirEspec(Integer.valueOf(idExc), cid1, cid2) == true){
                JOptionPane.showMessageDialog(null, "Exclusão Realizada", idExc, JOptionPane.NO_OPTION);
                refresh();
            }else{
                JOptionPane.showMessageDialog(null, "Erro de Exclusão", idExc, JOptionPane.NO_OPTION);
            }
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserirPrefixo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbPrefixo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
