/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Itinerarios;

import Dao.Class.Linha;
import Dao.Controller.LinhaControlador;
import View.TelaVenda;
import java.sql.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Baroni
 * 
 */

public class ItinerarioBus extends javax.swing.JDialog {

    LinhaControlador LC = new LinhaControlador();

    public int servico;
    public int pref;
    public Date dia;
    public int origem;
    public int destino;
    public String usuario;

    /**
     * Creates new form ItinerarioBus
     */

    public ItinerarioBus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void buscarDadosItinerario(){
        List<Linha> lin = LC.buscaItinerarioBus(pref);
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        Object rowData[] = new Object[5];
        model.setRowCount(0);
        for(int i =0; i< lin.size(); i++){
            rowData[0] = lin.get(i).getCidadeInicial();
            rowData[1] = lin.get(i).getCidade1().getCidade();
            rowData[2] = lin.get(i).getCidadeFinal();
            rowData[3] = lin.get(i).getCidade2().getCidade();
            rowData[4] = lin.get(i).getDuracao();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod. Origem", "Cidade Origem", "Cod. Destino", "Cidade Destino", "Duração"
            }
        ));
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVoltar.setText("<-");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        TelaVenda form = new TelaVenda();
        form.usuario = this.usuario;
        /*form.origem = v1;
        form.destino = v2;
        form.pref = prefixo;
        form.servico = servico;
        form.dia = sqlDia;*/
        form.itinBuscaTelaVenda(origem, destino, dia, servico);
        form.setValores();
        this.dispose();
        //form.setLocationRelativeTo(null);
        //form.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
