/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.Class.Funcionario;
import Dao.Controller.FuncionarioControlador;
import View.Caixa.FechamentoDeUsuarios;
import View.Cliente.SearchCliente;
import View.Funcionario.GerenciarFuncionario;
import View.Itinerarios.GerenciarCidades;
import View.Itinerarios.GerenciarLinhas;
import View.Menu.BuscarBilhetes;
import View.Menu.MapaDeViagem;
import View.Menu.RegisterTripMessage;
import View.Servicos.GerenciarServicos;
import View.Venda.CancelamentoBilhete;
import View.Venda.DevolucaoBilhete;
import View.Venda.RemarcarBilhetes;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Leandro Baroni
 */
public class MenuPrincipal extends javax.swing.JDialog {
    FuncionarioControlador FC = new FuncionarioControlador();
    Funcionario F = new Funcionario();
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date();
    public String usuario;
    public String login;
    String data_abertura = dateFormat.format(date);
    String num;
    
    /**
     * Creates new form MenuVendedor
     */

    public MenuPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void setUsuarios(){
        F = FC.buscar(usuario);
        lblUsuario.setText(F.getNome());
        setBotoes();
    }

    public void setBotoes(){
        SimpleDateFormat form = new SimpleDateFormat("dd/mm/yy");
        String tipo = F.getTipo();
        System.out.println("TIPO: " + tipo);
        lblData.setText(data_abertura);
        if("vendedor".equalsIgnoreCase(tipo)){
            System.out.println("entrou no IF");
            jCRUDColab.setEnabled(false);
            jCRUDColab.setVisible(false);
            jManutencao.setVisible(false);
            jManutencao.setEnabled(false);
        }else{
            System.out.println("veio no else");
        }
    }
    public void setValores(){
        setUsuarios();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenu1 = new javax.swing.JMenu();
        btLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jBarraDeMenu = new javax.swing.JMenuBar();
        jVendas = new javax.swing.JMenu();
        jVenda = new javax.swing.JMenuItem();
        jCancelar = new javax.swing.JMenuItem();
        jTroca = new javax.swing.JMenuItem();
        DevolverBilhete = new javax.swing.JMenuItem();
        jBuscarBilhete = new javax.swing.JMenu();
        jMapaViagem = new javax.swing.JMenuItem();
        jMenuViagem = new javax.swing.JMenuItem();
        jBuscarBilhetes = new javax.swing.JMenuItem();
        jCaixa = new javax.swing.JMenu();
        ConsultarResultadosDeVendas = new javax.swing.JMenuItem();
        jFecharUsuario = new javax.swing.JMenuItem();
        jBuscarFechamentos = new javax.swing.JMenuItem();
        jPesquisarColaborador = new javax.swing.JMenu();
        jPesquisarClientes = new javax.swing.JMenuItem();
        jCRUDColab = new javax.swing.JMenuItem();
        jManutencao = new javax.swing.JMenu();
        moverServico = new javax.swing.JMenuItem();
        moverLinhas = new javax.swing.JMenuItem();
        moverCidades = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        setResizable(false);

        btLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btLogout.setText("Sair");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jVendas.setText("Vendas");

        jVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jVenda.setText("Realizar Venda");
        jVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVendaActionPerformed(evt);
            }
        });
        jVendas.add(jVenda);

        jCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jCancelar.setText("Cancelar Bilhete");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });
        jVendas.add(jCancelar);

        jTroca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jTroca.setText("Remarcar Bilhete");
        jTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrocaActionPerformed(evt);
            }
        });
        jVendas.add(jTroca);

        DevolverBilhete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        DevolverBilhete.setText("Devolução de Bilhete");
        DevolverBilhete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverBilheteActionPerformed(evt);
            }
        });
        jVendas.add(DevolverBilhete);

        jBarraDeMenu.add(jVendas);

        jBuscarBilhete.setText("Menu");

        jMapaViagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMapaViagem.setText("Mapa de Viagem");
        jMapaViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMapaViagemActionPerformed(evt);
            }
        });
        jBuscarBilhete.add(jMapaViagem);

        jMenuViagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuViagem.setText("Viagem");
        jMenuViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuViagemActionPerformed(evt);
            }
        });
        jBuscarBilhete.add(jMenuViagem);

        jBuscarBilhetes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jBuscarBilhetes.setText("Buscar Bilhetes");
        jBuscarBilhetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarBilhetesActionPerformed(evt);
            }
        });
        jBuscarBilhete.add(jBuscarBilhetes);

        jBarraDeMenu.add(jBuscarBilhete);

        jCaixa.setText("Caixa");

        ConsultarResultadosDeVendas.setText("Consultar Valores de Venda");
        jCaixa.add(ConsultarResultadosDeVendas);

        jFecharUsuario.setText("Fechar Caixa");
        jCaixa.add(jFecharUsuario);

        jBuscarFechamentos.setText("Fechamento de Caixas");
        jBuscarFechamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarFechamentosActionPerformed(evt);
            }
        });
        jCaixa.add(jBuscarFechamentos);

        jBarraDeMenu.add(jCaixa);

        jPesquisarColaborador.setText("Cadastros");

        jPesquisarClientes.setText("Cadastros de Clientes");
        jPesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarClientesActionPerformed(evt);
            }
        });
        jPesquisarColaborador.add(jPesquisarClientes);

        jCRUDColab.setText("Colaborador");
        jCRUDColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRUDColabActionPerformed(evt);
            }
        });
        jPesquisarColaborador.add(jCRUDColab);

        jBarraDeMenu.add(jPesquisarColaborador);

        jManutencao.setText("Manutenção");

        moverServico.setText("Serviços");
        moverServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverServicoActionPerformed(evt);
            }
        });
        jManutencao.add(moverServico);

        moverLinhas.setText("Linhas");
        moverLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverLinhasActionPerformed(evt);
            }
        });
        jManutencao.add(moverLinhas);

        moverCidades.setText("Cidades");
        moverCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverCidadesActionPerformed(evt);
            }
        });
        jManutencao.add(moverCidades);

        jBarraDeMenu.add(jManutencao);

        setJMenuBar(jBarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLogout)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(btLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                    .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPesquisarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarClientesActionPerformed
        //JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        SearchCliente form = new SearchCliente(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_jPesquisarClientesActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        this.toBack();
        int i = JOptionPane.showConfirmDialog(null, "Fechado o SVP, perderá valores dos dados registrados.\nDeseja sair?", 
                "Fechar SVP", JOptionPane.YES_NO_OPTION);
        if(i == JOptionPane.YES_OPTION){
            Index tela = new Index();
            this.dispose();
            tela.setLocationRelativeTo(null);
            tela.setVisible(true);
        }else if(i == JOptionPane.NO_OPTION){
            System.out.println("cancelado");
        }
    }//GEN-LAST:event_btLogoutActionPerformed

    private void jVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVendaActionPerformed
        TelaVenda form = new TelaVenda();
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_jVendaActionPerformed

    private void jCRUDColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRUDColabActionPerformed
        GerenciarFuncionario form = new GerenciarFuncionario(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_jCRUDColabActionPerformed

    private void moverServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverServicoActionPerformed
        GerenciarServicos form = new GerenciarServicos(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_moverServicoActionPerformed

    private void moverLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverLinhasActionPerformed
        GerenciarLinhas form = new GerenciarLinhas(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_moverLinhasActionPerformed

    private void moverCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverCidadesActionPerformed
        GerenciarCidades form = new GerenciarCidades(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_moverCidadesActionPerformed

    private void jMapaViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMapaViagemActionPerformed
        MapaDeViagem tela = new MapaDeViagem();
        tela.usuario = this.usuario;
        //this.dispose();
        this.hide();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jMapaViagemActionPerformed

    private void jMenuViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuViagemActionPerformed
        RegisterTripMessage tela = new RegisterTripMessage();
        tela.usuario = this.usuario;
        tela.setValores();
        this.hide();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuViagemActionPerformed

    private void jBuscarBilhetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarBilhetesActionPerformed
        System.out.println("----------");
        BuscarBilhetes tela = new BuscarBilhetes();
        tela.usuario = this.usuario;
        tela.setValores();
        System.out.println("0");
        this.dispose();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        System.out.println("------------");
    }//GEN-LAST:event_jBuscarBilhetesActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        CancelamentoBilhete tela = new CancelamentoBilhete();
        tela.usuario = this.usuario;
        tela.setValores();
        this.dispose();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jCancelarActionPerformed

    private void DevolverBilheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverBilheteActionPerformed
        DevolucaoBilhete tela = new DevolucaoBilhete();
        tela.usuario = this.usuario;
        tela.setValores();
        this.dispose();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_DevolverBilheteActionPerformed

    private void jTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrocaActionPerformed
        RemarcarBilhetes tela = new RemarcarBilhetes();
        tela.usuario = this.usuario;
        tela.setValores();
        this.dispose();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jTrocaActionPerformed

    private void jBuscarFechamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarFechamentosActionPerformed
        FechamentoDeUsuarios tela = new FechamentoDeUsuarios();
        tela.usuario = this.usuario;
        tela.setValores();
        this.dispose();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_jBuscarFechamentosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConsultarResultadosDeVendas;
    private javax.swing.JMenuItem DevolverBilhete;
    private javax.swing.JButton btLogout;
    private javax.swing.JMenuBar jBarraDeMenu;
    private javax.swing.JMenu jBuscarBilhete;
    private javax.swing.JMenuItem jBuscarBilhetes;
    private javax.swing.JMenuItem jBuscarFechamentos;
    private javax.swing.JMenuItem jCRUDColab;
    private javax.swing.JMenu jCaixa;
    private javax.swing.JMenuItem jCancelar;
    private javax.swing.JMenuItem jFecharUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jManutencao;
    private javax.swing.JMenuItem jMapaViagem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuViagem;
    private javax.swing.JMenuItem jPesquisarClientes;
    private javax.swing.JMenu jPesquisarColaborador;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jTroca;
    private javax.swing.JMenuItem jVenda;
    private javax.swing.JMenu jVendas;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem moverCidades;
    private javax.swing.JMenuItem moverLinhas;
    private javax.swing.JMenuItem moverServico;
    // End of variables declaration//GEN-END:variables
}