/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cliente;

import Dao.Class.Cliente;
import Dao.Controller.ClienteControlador;
import Dao.Class.Funcionario;
import Dao.Controller.FuncionarioControlador;
import View.MenuPrincipal;
import java.math.BigInteger;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Baroni
 */
public class SearchCliente extends javax.swing.JDialog {

    Cliente c = new Cliente();
    Funcionario F = new Funcionario();
    ClienteControlador cc = new ClienteControlador();
    FuncionarioControlador FC = new FuncionarioControlador();
    public String usuario;
    /**
     * Creates new form cadCliente
     */
    public SearchCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setValores(){
        F = FC.buscar(usuario);
        String tipo = F.getTipo();
        if("vendedor".equals(tipo)){
            System.out.println("entrou no IF");
            btDeleteProfile.setEnabled(false);
            btDeleteProfile.setBorderPainted(false);
            btDeleteProfile.setVisible(false);
        }else{
            System.out.println("veio no else");
        }
        refresh();
    }

    public void refresh(){
        txtBuscarNome.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JToggleButton();
        btNovoCadastro = new javax.swing.JToggleButton();
        btEditProfile = new javax.swing.JToggleButton();
        txtBuscarNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btBuscarNome = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btDeleteProfile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setText("Clientes");

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btNovoCadastro.setText("Novo");
        btNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoCadastroActionPerformed(evt);
            }
        });

        btEditProfile.setText("Editar");
        btEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditProfileActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite o Nome: ");

        btBuscarNome.setText("Buscar");
        btBuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarNomeActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "RG", "CPF/CNPJ", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        btDeleteProfile.setText("Excluir");
        btDeleteProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteProfileActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF:");

        txtDoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btDeleteProfile)
                        .addGap(18, 18, 18)
                        .addComponent(btEditProfile)
                        .addGap(18, 18, 18)
                        .addComponent(btNovoCadastro)
                        .addGap(18, 18, 18)
                        .addComponent(btVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscarNome)
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btBuscarNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(btNovoCadastro)
                    .addComponent(btEditProfile)
                    .addComponent(btDeleteProfile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoCadastroActionPerformed
        CadCliente form = new CadCliente(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_btNovoCadastroActionPerformed

    private void btBuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarNomeActionPerformed
        String nome = txtBuscarNome.getText();
        System.out.println("NOME: "+nome);
        if(nome != null && !nome.isEmpty()){
            if(txtDoc.getText().trim().equals("")){
                if(nome.length() >= 3){
                    List<Cliente> cli = cc.buscarNomeParcial(nome);
                    DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                    Object rowData[] = new Object[5];
                    model.setRowCount(0);
                    for(int i =0; i< cli.size(); i++){
                        rowData[0] = cli.get(i).getId();
                        rowData[1] = cli.get(i).getNome();
                        rowData[2] = cli.get(i).getRg();
                        rowData[3] = cli.get(i).getCpf_cnpj();
                        rowData[4] = cli.get(i).getTelefone();
                        model.addRow(rowData);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nome Curto Para Realizar Busca !!!", "Erro", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                String cpf = txtDoc.getText();
                if(nome.length() >= 3){
                    List<Cliente> cli = cc.buscarNomeEDoc(nome, cpf);
                    DefaultTableModel model = (DefaultTableModel) jTable.getModel();
                    Object rowData[] = new Object[5];
                    model.setRowCount(0);
                    for(int i =0; i< cli.size(); i++){
                        rowData[0] = cli.get(i).getId();
                        rowData[1] = cli.get(i).getNome();
                        rowData[2] = cli.get(i).getRg();
                        rowData[3] = cli.get(i).getCpf_cnpj();
                        rowData[4] = cli.get(i).getTelefone();
                        model.addRow(rowData);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nome Curto Para Realizar Busca !!!", "Erro", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Digite os campos da busca", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btBuscarNomeActionPerformed

    private void jTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMousePressed
        jTable.editingCanceled(null);
    }//GEN-LAST:event_jTableMousePressed

    private void btEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditProfileActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int linhaSelec = jTable.getSelectedRow();
        if(jTable.getSelectedRow() == -1){
            if(jTable.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Tabela está vazia", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um Perfil !!!", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            UpdCliente form = new UpdCliente(null, true);
            String idEsc = model.getValueAt(linhaSelec, 0).toString();
            form.valorId = Integer.parseInt(idEsc);
            form.usuario = F.getLogin();
            form.setValores();
            this.dispose();
            form.setLocationRelativeTo(null);
            form.setVisible(true);
        }
    }//GEN-LAST:event_btEditProfileActionPerformed

    private void btDeleteProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteProfileActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int linhaSelec = jTable.getSelectedRow();
        if(jTable.getSelectedRow() == -1){
            if(jTable.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(null, "TABELA ESTÁ VAZIA", "NÃO ENCONTRADO", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "SELECIONE UM PERFIL !!!", "NÃO ENCONTRADO", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            int i = JOptionPane.showConfirmDialog(null, "Deseja Realmente Ecluir Registro de Cliente?", 
                    "Exclusão", JOptionPane.YES_NO_OPTION);
            if(i == JOptionPane.YES_OPTION){
                String idExc = model.getValueAt(linhaSelec, 0).toString();
                cc.excluir(Integer.valueOf(idExc));
                refresh();
            }else if(i == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(null, "EXCLUSÃO CANCELADA", "FECHAR", JOptionPane.CLOSED_OPTION);
            }
        }
    }//GEN-LAST:event_btDeleteProfileActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        MenuPrincipal form = new MenuPrincipal(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btBuscarNome;
    private javax.swing.JButton btDeleteProfile;
    private javax.swing.JToggleButton btEditProfile;
    private javax.swing.JToggleButton btNovoCadastro;
    private javax.swing.JToggleButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txtBuscarNome;
    private javax.swing.JFormattedTextField txtDoc;
    // End of variables declaration//GEN-END:variables
}
