/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Servicos;

import Dao.Class.Cidade;
import Dao.Class.Funcionario;
import Dao.Class.Linha;
import Dao.Class.Servico;
import Dao.Controller.CidadeControlador;
import Dao.Controller.FuncionarioControlador;
import Dao.Controller.LinhaControlador;
import Dao.Controller.ServicoControlador;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro Baroni
 */

public class RegistrarServicos extends javax.swing.JDialog {

    Funcionario F = new Funcionario();
    FuncionarioControlador FC = new FuncionarioControlador();
    Servico S = new Servico();
    ServicoControlador SC = new ServicoControlador();    
    Linha L = new Linha();
    LinhaControlador LC = new LinhaControlador();    
    Cidade C = new Cidade();
    CidadeControlador CC = new CidadeControlador();
        
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    public String usuario;

    /**
     * Creates new form GerenciarServicos
     */

    public RegistrarServicos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setValores(){
        setUsuario();
        refresh();
        setPref();
    }

    public void setUsuario(){
        F = FC.buscar(usuario);
        String tipo = F.getTipo();
        System.out.println("USUARIO: " + F.getLogin() + ""
                + "Tipo: "+ tipo);        
    }

    public void setPref(){
        for (Linha c: LC.buscarPrefx()){
            cbPrefixo.addItem(Integer.toString(c.getPrefixo()));
        }        
    }

    public void refresh(){
        List<Linha> li = LC.buscarPrefx();
        jDateChooser.cleanup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser = new com.toedter.calendar.JDateChooser();
        txtHora = new javax.swing.JFormattedTextField();
        btVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbPrefixo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodServico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btRegistrar = new javax.swing.JButton();
        cbPoltDisp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txtHora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btVoltar.setText("Sair");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Data/Horário:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Prefixo: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Polt. Disponiveis: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Cod. Serviço: ");

        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        cbPoltDisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "27", "38", "42" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegistrar)
                .addGap(18, 18, 18)
                .addComponent(btVoltar)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(46, 46, 46)
                            .addComponent(txtCodServico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(cbPoltDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrefixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPoltDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar)
                    .addComponent(btRegistrar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        GerenciarServicos form = new GerenciarServicos(null, true);
        form.usuario = F.getLogin();
        form.setValores();
        this.dispose();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = jDateChooser.getDate();
        String dia = sdf.format(date);
        String hora = txtHora.getText() + ":00";
        int qtdPolt = Integer.parseInt(cbPoltDisp.getSelectedItem().toString());
        int cod;

        if(txtCodServico.getText().trim().equals("")){
            cod = 0;
        }else {
            System.out.println("03");
            cod = Integer.parseInt(txtCodServico.getText());
        }

        int poltOcup = 0;
        int nCarro = 0;
        String motorista = "";
        String mensagem = "";
        int prefixo = Integer.parseInt(cbPrefixo.getSelectedItem().toString());
        
        L = LC.buscarCidade(prefixo);
        int cidadeIni = L.getCidadeInicial();
        C = CC.buscarCidade(Integer.toString(cidadeIni));

        System.out.println("\nDATA: " + dia);
        System.out.println("HORA: " + hora);
        System.out.println("Prefixo: " + prefixo);
        System.out.println("cod: " + cod);
        System.out.println("qtdPolt: " + qtdPolt);
        System.out.println("Ocupado: " + poltOcup);

        if(dia != null && !dia.isEmpty() && hora != null && !hora.isEmpty()){
            if(cod > 0 && qtdPolt > 0){
                Servico novo = new Servico(cod, dia, hora, qtdPolt, poltOcup, nCarro, motorista, mensagem, prefixo);
                if(SC.inserir(novo) == true){
                    JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!", "OK", JOptionPane.OK_OPTION);
                    refresh();
                }else{
                    System.out.println("erro de inserir");
                    JOptionPane.showMessageDialog(null, "Cadastro cadastro não efetuado!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }else if(cod == 0){
                JOptionPane.showMessageDialog(null, "Digite o CODIGO de serviço", "", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Erro", JOptionPane.CLOSED_OPTION);
        }
    }//GEN-LAST:event_btRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbPoltDisp;
    private javax.swing.JComboBox<String> cbPrefixo;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCodServico;
    private javax.swing.JFormattedTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
