/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Menu;

import Dao.Class.BilhetePdf;
import Dao.Class.Venda;
import Dao.Controller.BilhetePdfControlador;
import Dao.Controller.VendaControlador;
import View.MenuPrincipal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro Baroni
 */
public class BuscarBilhetes extends javax.swing.JFrame {

    List<Venda> V = new ArrayList<>();
    VendaControlador VC = new VendaControlador();
    BilhetePdf B = new BilhetePdf();
    BilhetePdfControlador BC = new BilhetePdfControlador();

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");

    public String usuario;

    /**
     * Creates new form BuscarBilhetes
     */
    public BuscarBilhetes() {
        initComponents();
    }

    public void setValores(){
        setButtonOff();
    }

    public void setButtonOff(){
        btImprimir2Via.setEnabled(false);
        jTable.setVisible(false);
        jTable.setEnabled(false);
    }

    public void setButtonOn(){
        btImprimir2Via.setEnabled(true);
        jTable.setVisible(true);
        jTable.setEnabled(true);
        setValueTable();
    }

    public void setValueTable(){
        //List<Funcionario> fun = FC.buscarNomeParcial(nome);
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        Object rowData[] = new Object[8];
        model.setRowCount(0);
        for(int i =0; i< V.size(); i++){
            rowData[0] = V.get(i).getCodBilhete();
            rowData[1] = V.get(i).getServico();
            rowData[2] = V.get(i).getNomeCliente();
            rowData[3] = V.get(i).getRg();
            rowData[4] = V.get(i).getCpfCnpj();
            rowData[5] = V.get(i).getDataVenda();
            rowData[6] = V.get(i).getHoraVenda();
            rowData[7] = V.get(i).getNumPoltrona();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        btImprimir2Via = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserCompra = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodBilhete = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Dados de Bilhetes");
        setResizable(false);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bilhete", "Serviço", "Nome", "Rg", "CPF", "Data da Venda", "Hora da Venda", "Poltrona"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
            jTable.getColumnModel().getColumn(1).setResizable(false);
            jTable.getColumnModel().getColumn(2).setResizable(false);
            jTable.getColumnModel().getColumn(3).setResizable(false);
            jTable.getColumnModel().getColumn(4).setResizable(false);
            jTable.getColumnModel().getColumn(5).setResizable(false);
            jTable.getColumnModel().getColumn(6).setResizable(false);
            jTable.getColumnModel().getColumn(7).setResizable(false);
        }

        btSair.setText("Voltar");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btImprimir2Via.setText("2ª Via");
        btImprimir2Via.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimir2ViaActionPerformed(evt);
            }
        });

        btConfirmar.setText("Buscar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        jLabel2.setText("Data da Compra: ");

        jLabel3.setText("Nome: ");

        jLabel4.setText("Bilhete: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jDateChooserCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btImprimir2Via, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodBilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btConfirmar))
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btImprimir2Via))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        MenuPrincipal tela = new MenuPrincipal(null, true);
        tela.usuario = this.usuario;
        tela.setValores();
        this.dispose();
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        Date dataCompra = jDateChooserCompra.getDate();
        String dCompra = sdf.format(dataCompra);
        System.out.println("____________________________________");

        try{
            if (jDateChooserCompra.getDate() == null) {
                System.out.println("1");
                JOptionPane.showMessageDialog(null , "Insira uma data de viagem ou de compra.", "Erro", JOptionPane.INFORMATION_MESSAGE);            
                jDateChooserCompra.grabFocus();
            }else{
                int codBilhete;
                String nome;
                System.out.println("2");
                if(!txtCodBilhete.getText().trim().equals("") && !txtNome.getText().trim().equalsIgnoreCase("")){
                    System.out.println("4");
                    codBilhete = Integer.parseInt(txtCodBilhete.getText());
                    nome = txtNome.getText();
                    V = VC.buscarServico(dCompra, codBilhete, nome);
                    setButtonOn();
                }else if(!txtCodBilhete.getText().trim().equals("") && txtNome.getText().trim().equals("")){
                    codBilhete = Integer.parseInt(txtCodBilhete.getText());
                    System.out.println("5");
                    V = VC.buscarServico(dCompra, codBilhete);
                    setButtonOn();
                }else if(txtCodBilhete.getText().trim().equals("") && !txtNome.getText().trim().equalsIgnoreCase("")){
                    nome = txtNome.getText();
                    System.out.println("6");
                    V = VC.buscarServico(dCompra, nome);
                    setButtonOn();
                }else{
                    System.out.println("fim");
                    JOptionPane.showMessageDialog(null , "Digite o Nome/Bilhete!!!", "Erro", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch(NumberFormatException ex){
            System.out.println("Erro: " + ex);
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btImprimir2ViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimir2ViaActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int linhaSelec = jTable.getSelectedRow();
        if(jTable.getSelectedRow() == -1){
            if(jTable.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Tabela está vazia", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um Perfil !!!", "Não Encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            String nome = model.getValueAt(linhaSelec, 2).toString();
            int polt = Integer.parseInt(model.getValueAt(linhaSelec, 7).toString());
            int serv = Integer.parseInt(model.getValueAt(linhaSelec, 1).toString());
            String dataAt = model.getValueAt(linhaSelec, 5).toString();
            String hourAt = model.getValueAt(linhaSelec, 6).toString();
            B = BC.getDadosBilhete(nome, polt, serv, dataAt, hourAt);
            System.out.println("------------");

            BC.createPdfFile(B);
        }        
    }//GEN-LAST:event_btImprimir2ViaActionPerformed

    private void jTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMousePressed
        jTable.editingCanceled(null);
    }//GEN-LAST:event_jTableMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btImprimir2Via;
    private javax.swing.JButton btSair;
    private com.toedter.calendar.JDateChooser jDateChooserCompra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JFormattedTextField txtCodBilhete;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
